### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by jliebana** [romain-fontugne/slpa_nx#1]
Hi!

I think you have [a little bug in the line 31](https://github.com/romain-fontugne/slpa_nx/blob/master/slpa.py#L31) because the speakers list might be empty if the node is isolated. 

This is as simple to fix as adding a " if(len(speakers)>0):" in line 23, ending this "if-block" at the end of the "for-block". If there are no speakers (the node is isolated), just skip that node and leave it with the current label.

Thanks for the code anyway :)

Regards!

**Comment by romain-fontugne** [comment]
Hi,

Thanks for the report. I have made a fix, it should work now!

Cheers
